-- 初期データの投入
INSERT INTO POSTS (ID, TITLE, CONTENT, CREATED_AT) VALUES (1, 'はじめての投稿', 'こんにちは！H2データベース。', CURRENT_TIMESTAMP);
INSERT INTO POSTS (ID, TITLE, CONTENT, CREATED_AT) VALUES (2, '2番目のメモ', '自動投入は便利ですね。', CURRENT_TIMESTAMP);